name: Build/Release
on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install electron dependencies
        run: npm install
      - name: install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: build-frontend
        run: |
          cd frontend
          npm run build
      - name: build-app
        run: npm run electron:build
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run electron:publish
